#	|------------------------------------|
#	| Clone ALL Eventbrite Repo's Script |
#	|------------------------------------|

git clone https://github.com/eventbrite/facebook-python-sdk.git
git clone https://github.com/eventbrite/django-cache-machine.git
git clone https://github.com/eventbrite/nexus.git
git clone https://github.com/eventbrite/django-debug-toolbar.git
git clone https://github.com/eventbrite/django-sentry.git
git clone https://github.com/eventbrite/macfsevents.git
git clone https://github.com/eventbrite/eventbrite-client-py.git
git clone https://github.com/eventbrite/django-audit-log.git
git clone https://github.com/eventbrite/django-assemblyline.git
git clone https://github.com/eventbrite/zendesk.git
git clone https://github.com/eventbrite/kegbot.git
git clone https://github.com/eventbrite/rebar.git
git clone https://github.com/eventbrite/mongoengine.git
git clone https://github.com/eventbrite/transifex-python-library.git
git clone https://github.com/eventbrite/celery.git
git clone https://github.com/eventbrite/gerrit_repo.git
git clone https://github.com/eventbrite/tablesnap.git
git clone https://github.com/eventbrite/m2crypto.git
git clone https://github.com/eventbrite/py-smartdc.git
git clone https://github.com/eventbrite/sentry-jira.git
git clone https://github.com/eventbrite/puppetlabs-apt.git
git clone https://github.com/eventbrite/puppetlabs-stdlib.git
git clone https://github.com/eventbrite/puppet-sudo.git
git clone https://github.com/eventbrite/raven-java.git
git clone https://github.com/eventbrite/django-nose.git
git clone https://github.com/eventbrite/pydot.git
git clone https://github.com/eventbrite/duo_python.git
git clone https://github.com/eventbrite/nose-knows.git
git clone https://github.com/eventbrite/SOAPpy.git
git clone https://github.com/eventbrite/puppet-supervisor.git
git clone https://github.com/eventbrite/eventioz-archive-pdf-writer.git
git clone https://github.com/eventbrite/python_hive_utils.git
git clone https://github.com/eventbrite/deskapi.git
git clone https://github.com/eventbrite/eventbrite.php.git
git clone https://github.com/eventbrite/eventbrite-client.rb.git
git clone https://github.com/eventbrite/Eventbrite.jquery.js.git
git clone https://github.com/eventbrite/eventbrite.npm.git
git clone https://github.com/eventbrite/pinocchio.git
git clone https://github.com/eventbrite/vagrant-ebcommon.git
git clone https://github.com/eventbrite/vagrant-puppet-fact-generator.git
git clone https://github.com/eventbrite/vagrant-puppet-module-registry.git
git clone https://github.com/eventbrite/vagrant-soa.git
git clone https://github.com/eventbrite/eventually.git
git clone https://github.com/eventbrite/sphinx_rtd_theme.git
git clone https://github.com/eventbrite/gargoyle.git
git clone https://github.com/eventbrite/nose-picker.git
git clone https://github.com/eventbrite/cs2mako.git
git clone https://github.com/eventbrite/rangeslider.js.git
git clone https://github.com/eventbrite/dorsal.git
git clone https://github.com/eventbrite/curator.git
git clone https://github.com/eventbrite/graphite-reporter-agent.git
git clone https://github.com/eventbrite/currint.git
git clone https://github.com/eventbrite/tikibar.git
git clone https://github.com/eventbrite/jenkinsapi.git
git clone https://github.com/eventbrite/kss-search.git
git clone https://github.com/eventbrite/grunt-kss-search.git
git clone https://github.com/eventbrite/locust.git
git clone https://github.com/eventbrite/localization_shuttle.git
git clone https://github.com/eventbrite/eventbrite-sdk-python.git
git clone https://github.com/eventbrite/eventioz-archive-cielo.git
git clone https://github.com/eventbrite/eventioz-archive-mercadopago.git
git clone https://github.com/eventbrite/pilo.git
git clone https://github.com/eventbrite/invoke-release.git
git clone https://github.com/eventbrite/eb-lookup.git
git clone https://github.com/eventbrite/redux-form.git
git clone https://github.com/eventbrite/Diamond.git
git clone https://github.com/eventbrite/analytics.js.git
git clone https://github.com/eventbrite/javascript.git
git clone https://github.com/eventbrite/kss-node.git
git clone https://github.com/eventbrite/css.git
git clone https://github.com/eventbrite/python-instagram.git
git clone https://github.com/eventbrite/Casper-API-Tools.git
git clone https://github.com/eventbrite/facebook-py-sdk.git
git clone https://github.com/eventbrite/conformity.git
git clone https://github.com/eventbrite/eventbrite-sdk-php.git
git clone https://github.com/eventbrite/nose-annotator.git
git clone https://github.com/eventbrite/raphael.git
git clone https://github.com/eventbrite/pysoa.git
git clone https://github.com/eventbrite/eventbrite-sdk-ruby.git
git clone https://github.com/eventbrite/bay.git
git clone https://github.com/eventbrite/grunt-contrib-requirejs.git
git clone https://github.com/eventbrite/consistent-hash.git
git clone https://github.com/eventbrite/presto.git
git clone https://github.com/eventbrite/mapzen-tools.git
git clone https://github.com/eventbrite/eventbrite-sdk-javascript.git
git clone https://github.com/eventbrite/presto-hadoop-apache2.git
git clone https://github.com/eventbrite/react-lottie.git
git clone https://github.com/eventbrite/pycrypto.git
git clone https://github.com/eventbrite/brite-cli.git
git clone https://github.com/eventbrite/spark-atlas-connector.git
git clone https://github.com/eventbrite/enzyme-fetch-mock.git
git clone https://github.com/eventbrite/uwsgi-dogstatsd.git
git clone https://github.com/eventbrite/pybars3.git
git clone https://github.com/eventbrite/pymetrics.git
git clone https://github.com/eventbrite/ioredis.git
git clone https://github.com/eventbrite/py-crawler-detect.git
git clone https://github.com/eventbrite/private-terraform-enterprise.git
git clone https://github.com/eventbrite/britecharts.git
git clone https://github.com/eventbrite/britecharts-react.git
