# To manually build docs locally:
# mkvirtualenv3 conformity-docs
# pip install -e .[docs]
# cd docs
# make html
# open _build/html/index.html

version: 2
sphinx:
  builder: html
  configuration: docs/conf.py
python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
